enum NotificationType {
  MATCH_FOUND,
  PASSENGER_JOIN,
  TRIP_CONFIRMED,
  TRIP_STARTED,
  TRIP_EXPIRED,
  TRIP_COMPLETED,
  PROMPT_TO_CONFIRM,
  PROMPT_TO_START,
  TRIP_STARTING_IN_10,
  DRIVER_ARRIVED_AT_PICKUP,
  DRIVER_CONFIRMED_PICKUP,
  DRIVER_CONFIRMED_DROP
}